### ISSUE TITLE
asInstanceOfOpt already exists: Option

### ISSUE THREAD

**Issue by cvogt** [t3hnar/scalax#7]
`Option(null) == None`
`Option("foo") == Some("foo")`

**Comment by t3hnar** [comment]
@cvogt not sure what do you mean

**Comment by cvogt** [comment]
I see `null.asInstanceOfOpt[String]` in your docs. That's equivalent to the build in

```
scala> Option[String](null)
res0: Option[String] = None

scala> val o: Option[String] = Option(null)
o: Option[String] = None
```

So maybe these should be removed. Or I am missing something.

**Comment by cvogt** [comment]
(FYI, your email address in the git history 3hnar@gmail.com bounces saying `The email account that you tried to reach does not exist`)

**Comment by t3hnar** [comment]
Sure I know about `Option(null)`, but it does not mean user won't call `null.asInstanceOfOpt[String]` :)

**Comment by cvogt** [comment]
@t3hnar does asInstanceOfOpt offer anything that Option(...) does not? Otherwise why does it exist?

**Comment by t3hnar** [comment]
@cvogt it is similar to `asInstanceOf` but if type does not match - you will get None rather then exception

```scala
trait A
class B extends A
class C extends A

val b: A = new B

b.asInstanceOfOpt[B] // Some
b.asInstanceOfOpt[C] // None
```

**Comment by cvogt** [comment]
Ah I see, nevermind then :)
